openapi: 3.0.0
info:
  title: Authentication Service API
  description: API for user authentication and token validation
  version: 1.0.0
servers:
  - url: http://localhost:8080/auth  # URL di esempio
paths:
  /authenticate:
    post:
      summary: Authenticate user
      description: Authenticates a user with email and password and returns a token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticateUserRequest'
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticateUserResponse'
        '401':
          description: Invalid credentials
  /validate:
    post:
      summary: Validate token
      description: Validates a user's authentication token.
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Bearer token
      responses:
        '200':
          description: Valid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateTokenResponse'
        '401':
          description: Invalid token
components:
  schemas:
    AuthenticateUserRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    AuthenticateUserResponse:
      type: object
      properties:
        token:
          type: string
    ValidateTokenRequest:
      type: object
      properties:
        token:
          type: string
      required:
        - token
    ValidateTokenResponse:
      type: object
      properties:
        valid:
          type: boolean
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT